<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Categorie extends Model
{
    protected $fillable = [
        'id',
        'slug',
        'code',
        'nom',
        'description',
        'logo'
    ];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($event){
           $event->slug = Str::uuid();
        });
    }


    public function institution()
    {
        return $this->hasMany(Institution::class);
    }

    public function user(){
        return $this->hasMany(User::class);
    }
}
