<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Conditions extends Model
{
    protected $fillable = [
      'id',
      'slug',
      'condition',
      'operation_id'
    ];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($event){
           $event->slug = Str::uuid();
        });
    }

    public function operation () {
        return $this->belongsTo(Operation::class);
    }
}

