<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Institution extends Model
{
    protected $fillable = [
        'id',
        'slug',
        'nom',
        'description',
        'adresse',
        'contact',
        'email',
        'siteweb',
        'logo',
        'categorie_id'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($event){
            $event -> slug = Str::uuid();
        });
    }

    public function categorie()
    {
        return $this->belongsTo(Categorie::class);
    }

    public function operation()
    {
        return $this->belongsToMany(Operation::class)->withTimestamps();
    }
}
