<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Operation extends Model
{
    protected $fillable = [
      'id',
      'slug',
      'code',
      'nom',
      'description',
      'montant',
      'visited',
      'user_id',
      'type_id'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($event){
           $event -> slug = Str::uuid();
        });
    }

    public function piece()
    {
        return $this->belongsToMany(Piece::class)->withTimestamps();
    }

    public function user()
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }

    public function conditions()
    {
        return $this->hasMany(Conditions::class);
    }

    public function type(){
        return $this->belongsTo(Type::class);
    }

}
