<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Type extends Model
{
    protected $fillable = [
      'id',
      'slug',
      'nom',
      'code',
      'description'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($event){
           $event -> slug = Str::uuid();
        });
    }

    public function operation(){
        return $this->hasMany(Operation::class);
    }
}
