<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Str;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id',
        'slug',
        'nom',
        'email',
        'password',
        'role',
        'adresse',
        'contact',
        'siteweb',
        'logo',
        'description',
        'categorie_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($event){
           $event -> slug = Str::uuid();
        });
    }


    public function categorie()
    {
        return $this->belongsTo(Categorie::class);
    }

    public function operation()
    {
        return $this->belongsToMany(Operation::class)->withTimestamps();
    }

}
